spring:
  application:
    name: crediya-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: crediya-auth
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/users/**

            - id: crediya-applications
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/applications/**

server:
  port: 8080

